# User settings
user:
  name: badger
  shell: /bin/bash

# Runtime variables depending on scenario
update_system: true

docker_unsecure: False # TBD var
update_docker: true # turn on if updating or fresh install
createorupdate_main_user: false

# Badgehub stuff
pg_backup_dir: /backup/badgehub_data/
deploy_dir: /home/badger
repo_url: https://github.com/badgeteam/badgehub-api.git # URL of the repository
repo_branch: main # Branch to checkout

filesystem:
  data_path: /data

# UFW
# This can be changed depending on if its dev or prod, defaulted to prod

ufw_ports:
  - 9002
  - 9001

# Packages

docker_packages:
  - docker.io
  - docker-compose

base_packages:
  - vim
  - git
  - tmux
  - nano
  - htop
  - curl
  - wget
  - tree
  - ncdu
  - zip
  - unzip
  - time
  - apt-utils
  - screen
  - man-db
  - dnsutils
  - telnet
  - tcpdump
  - traceroute
  - mtr
  - nmap
  - lsof
  - apt-transport-https
  - ca-certificates
  - net-tools
  - rsync
  - jq
  - sysstat
  - gpg
  - sudo

other:
  - fail2ban
  - sudo
  - logrotate
  - unattended-upgrades
  - rsyslog
