- name: Configure badgehub system
  hosts: badgehub_test
  remote_user: badger
  vars:
    ansible_port: 2222
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

  roles:
    - system
    - user
    - ufw
    - ssh
    - filesystem
    - docker
    - badgehub_api
