- name: Configure badgehub system
  hosts: all
  remote_user: badger

  roles:
    - system
    - user
    - ufw
    - ssh
    - filesystem
    - docker

  vars_prompt:
    - name: password
      prompt: What is the users password?
      private: true