- name: Configure badgehub system
  hosts: all
  remote_user: root

  roles:
    - system
    - user
    - ufw
    - ssh

  vars_prompt:
    - name: password
      prompt: What is your password?
      private: true