- name: Configure badgehub system
  hosts: badgehub_test
  remote_user: badger
  vars:
    ansible_port: 2222

  roles:
    - system
    - user
    - ufw
    - ssh
    - filesystem
    - docker
    - badgehub_api

 
