- name: Ensure all necessary groups are created
  group:
    name: "{{ item }}"
  loop:
    - "{{ user.name }}"
  become: true

- name: Ensure the non-root user is created
  user:
    name: "{{ user.name }}"
    password: "{{ password | password_hash('sha512') }}"
    groups:
      - sudo
    append: yes
    shell: "{{ user.shell }}"
    create_home: yes
    update_password: on_create
  become: true

- name: Enable passwordless sudo for "{{ user.name }}"
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ user.name }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"
  become: true

