- name: Confirm Execution
  pause:
    prompt: "Prompt for user password"
  register: pause_result
  run_once: true
  when: createorupdate_main_user

- name: Ensure all necessary groups are created
  ansible.builtin.group:
    name: "{{ item }}"
  loop:
    - "{{ user.name }}"
  become: true

- name: Ensure the non-root user is created
  ansible.builtin.user:
    name: "{{ user.name }}"
    password: "{{ pause_result.user_input | password_hash('sha512') }}"
    groups:
      - sudo
    append: true
    shell: "{{ user.shell }}"
    create_home: true
    update_password: always
  become: true
  when: createorupdate_main_user

- name: Enable passwordless sudo for "{{ user.name }}"
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "{{ user.name }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"
  become: true
