services:
  db-keycloak:
    image: postgres:16
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/keycloak-postgres:/var/lib/postgresql/data
    networks:
      - badgehub_network

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    restart: always
    env_file:
      - .env
    entrypoint: sh -c "/opt/keycloak/bin/kc.sh start"
    environment:
      - KEYCLOAK_OPTS=--proxy-headers xforwarded --http-enabled true --hostname keycloak.p1m.n
      - PROXY_ADDRESS_FORWARDING=true
      - KC_PROXY=edge
      - KC_METRICS_ENABLED=true
      - KC_HEALTH_ENABLED=true
      - KC_DB_SCHEMA=public
      - KC_DB_USERNAME=keycloak
      - KC_DB_URL_HOST=db-keycloak
      - KC_DB_URL_DATABASE=keycloak
      - KC_LOG_LEVEL=WARN
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT_HTTPS=false
      - QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY=true
    command:
      - start
    volumes:
      - ./auth/import:/opt/keycloak/data/import
      - ./themes:/opt/keycloak/themes
    depends_on:
      - db-keycloak
    networks:
      - badgehub_network
      - service-http
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`auth.badge.why2025.org`)"
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      - "traefik.http.routers.keycloak.tls.certresolver=letsencrypt"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      - "traefik.docker.network=service-http"

networks:
  badgehub_network:
    name: badgehub_network
    external: true
  service-http:
    external: true
