- name: Update repositories cache and install ssh
  ansible.builtin.apt:
    name: ssh
    update_cache: true
    cache_valid_time: 600
  become: true

- name: Set authorized keys from all public key files in a directory, removing others
  ansible.posix.authorized_key:
    user: "{{ user.name }}"
    key: "{{ lookup('file', item) }}"
    state: present
    exclusive: true
  with_fileglob:
    - "public_keys/*.pub"

- name: Update sshd configuration safely, avoid locking yourself out
  ansible.builtin.template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
    validate: /usr/sbin/sshd -t -f %s
    backup: true
  become: true

- name: Restart service
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: sshd
    enabled: true
  become: true

- name: Rate limit ssh
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp
  become: true
