- name: Ensure the directory structure exists
  ansible.builtin.file:
    path: "{{ filesystem.data_path }}"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: "0755"
  become: true
