- name: Update repositories cache and install ufw
  ansible.builtin.apt:
    name: ufw
    update_cache: true
    cache_valid_time: 600
  become: true

- name: Allow ssh port
  community.general.ufw:
    rule: allow
    name: OpenSSH
  become: true

- name: Enable UFW
  community.general.ufw:
    state: enabled
  become: true
