- name: Update repositories cache and install docker package
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    update_cache: true
    cache_valid_time: 600
  become: true
  when: update_docker

- name: Upload new template
  ansible.builtin.template:
    src: 'daemon.json.j2'
    dest: '/etc/docker/daemon.json'
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Restart Docker

- name: Check if user is in docker group
  ansible.builtin.command: groups {{ user.name }}
  register: user_groups

- name: Add the user to docker group
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: docker
    append: true
  become: true
  when: "'docker' not in user_groups.stdout"


- name: Copy systemd service for pruning docker stuff (does not do volumes)
  ansible.builtin.copy:
    src: files/docker-prune.service
    dest: /etc/systemd/system/docker-prune.service
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Reload systemd service for docker-prune

- name: Copy timer and systemd service for pruning docker stuff (does not do volumes)
  ansible.builtin.copy:
    src: files/docker-prune.timer
    dest: /etc/systemd/system/docker-prune.timer
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Start and enable systemd timer for docker-prune


