- name: Update repositories cache and install docker package
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    update_cache: true
    cache_valid_time: 600
  become: true

- name: Upload new template
  ansible.builtin.template:
    src: 'daemon.json.j2'
    dest: '/etc/docker/daemon.json'
    owner: root
    group: root
    mode: '0644'
  become: true # Unless you are connecting as root

- name: Add the user to docker group
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: docker
    append: true
  become: true
  when: docker_unsecure

- name: Copy systemd service for pruning docker stuff (does not do volumes)
  ansible.builtin.copy:
    src: files/docker-prune.service
    dest: /etc/systemd/system/docker-prune.service
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Copy timer and systemd service for pruning docker stuff (does not do volumes)
  ansible.builtin.copy:
    src: files/docker-prune.timer
    dest: /etc/systemd/system/docker-prune.timer
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Reload systemd service for docker-prune
  ansible.builtin.systemd:
    name: docker-prune.service
    state: reloaded
    enabled: true
    daemon_reload: true
  become: true

- name: Start and enable systemd timer for docker-prune
  ansible.builtin.systemd:
    name: docker-prune.timer
    state: started
    enabled: true
    daemon_reload: true
  become: true

- name: Restart docker service and reload daemon
  ansible.builtin.systemd:
    name: docker
    state: restarted
    enabled: true
    daemon_reload: true
  become: true
