services:
  badgehub-frontend:
    image: ghcr.io/badgeteam/badgehub-frontend:${FRONTEND_IMAGE_TAG:-latest}
    ports:
      - "8003:3000"
    restart: always
    env_file:
      - .env
    environment:
      FRONTEND_IMAGE_TAG: "${FRONTEND_IMAGE_TAG}"
    networks:
      - badgehub_external

  badgehub-api:
    image: ghcr.io/badgeteam/badgehub-api:${BACKEND_IMAGE_TAG:-latest}
    ports:
      - "9001:8081"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - badgehub_internal
      - badgehub_external

  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./mockup-data.sql:/docker-entrypoint-initdb.d/data.sql
      - ./backup:/var/backup
    networks:
      - badgehub_internal

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "9002:8082"
    env_file:
      - .env
    environment:
      - PGADMIN_LISTEN_PORT=8082
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - badgehub_internal
      - badgehub_external

networks:
  badgehub_internal:
  badgehub_external:

volumes:
  postgres_data:
  pgadmin_data:
